In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np
import UpROOT.io as io
import UpROOT.config as conf
import UpROOT.io as io

In [3]:
io.list_dataset_trees(
    dataset="dvntuple_01"
)

Archivo: 00334560_00000001_1.dvntuple.root
Árboles encontrados (2):
1. GetIntegratedLuminosity/LumiTuple
2. Btree/DecayTree

Archivo: 00334560_00000002_1.dvntuple.root
Árboles encontrados (2):
1. Btree/DecayTree
2. GetIntegratedLuminosity/LumiTuple

Archivo: 00334564_00000001_1.dvntuple.root
Árboles encontrados (2):
1. Btree/DecayTree
2. GetIntegratedLuminosity/LumiTuple

Archivo: 00334565_00000001_1.dvntuple.root
Árboles encontrados (2):
1. Btree/DecayTree
2. GetIntegratedLuminosity/LumiTuple

Archivo: 00334566_00000001_1.dvntuple.root
Árboles encontrados (2):
1. Btree/DecayTree
2. GetIntegratedLuminosity/LumiTuple

{PosixPath('/home/karna/Documentos/PF/data/00334560_00000001_1.dvntuple.root'): ['GetIntegratedLuminosity/LumiTuple',
  'Btree/DecayTree'],
 PosixPath('/home/karna/Documentos/PF/data/00334560_00000002_1.dvntuple.root'): ['Btree/DecayTree',
  'GetIntegratedLuminosity/LumiTuple'],
 PosixPath('/home/karna/Documentos/PF/data/00334564_00000001_1.dvntuple.root'): ['Btree/DecayTree',
  'GetIntegratedLuminosity/LumiTuple'],
 PosixPath('/home/karna/Documentos/PF/data/00334565_00000001_1.dvntuple.root'): ['Btree/DecayTree',
  'GetIntegratedLuminosity/LumiTuple'],
 PosixPath('/home/karna/Documentos/PF/data/00334566_00000001_1.dvntuple.root'): ['Btree/DecayTree',
  'GetIntegratedLuminosity/LumiTuple']}

In [4]:
io.list_branches(
    dataset='dvntuple_01',
    show_trees=True,
    show_branches=True,
    txt_path="dvntuple_01",
)

Árboles encontrados (2):
1. GetIntegratedLuminosity/LumiTuple
2. Btree/DecayTree
Archivo: 00334560_00000001_1.dvntuple.root
Árbol seleccionado: Btree/DecayTree
Ramas encontradas: 319
 - BCID
 - BCType
 - Bplus_DIRA_OWNPV
 - Bplus_ENDVERTEX_CHI2
 - Bplus_ENDVERTEX_COV_
 - Bplus_ENDVERTEX_NDOF
 - Bplus_ENDVERTEX_X
 - Bplus_ENDVERTEX_XERR
 - Bplus_ENDVERTEX_Y
 - Bplus_ENDVERTEX_YERR
 - Bplus_ENDVERTEX_Z
 - Bplus_ENDVERTEX_ZERR
 - Bplus_FDCHI2_OWNPV
 - Bplus_FD_OWNPV
 - Bplus_ID
 - Bplus_IPCHI2_OWNPV
 - Bplus_IP_OWNPV
 - Bplus_M
 - Bplus_MM
 - Bplus_MMERR
 - Bplus_OWNPV_CHI2
 - Bplus_OWNPV_COV_
 - Bplus_OWNPV_NDOF
 - Bplus_OWNPV_X
 - Bplus_OWNPV_XERR
 - Bplus_OWNPV_Y
 - Bplus_OWNPV_YERR
 - Bplus_OWNPV_Z
 - Bplus_OWNPV_ZERR
 - Bplus_P
 - Bplus_PE
 - Bplus_PT
 - Bplus_PX
 - Bplus_PY
 - Bplus_PZ
 - EventInSequence
 - GpsTime
 - HLT1TCK
 - HLT2TCK
 - J_psi_1S_DIRA_ORIVX
 - J_psi_1S_DIRA_OWNPV
 - J_psi_1S_ENDVERTEX_CHI2
 - J_psi_1S_ENDVERTEX_COV_
 - J_psi_1S_ENDVERTEX_NDOF
 - J_psi_1S_ENDVERTEX_X
 - J_psi_1S_ENDVERTEX_XERR
 - J_psi_1S_ENDVERTEX_Y
 - J_psi_1S_ENDVERTEX_YERR
 - J_psi_1S_ENDVERTEX_Z
 - J_psi_1S_ENDVERTEX_ZERR
 - J_psi_1S_FDCHI2_ORIVX
 - J_psi_1S_FDCHI2_OWNPV
 - J_psi_1S_FD_ORIVX
 - J_psi_1S_FD_OWNPV
 - J_psi_1S_ID
 - J_psi_1S_IPCHI2_OWNPV
 - J_psi_1S_IP_OWNPV
 - J_psi_1S_M
 - J_psi_1S_MM
 - J_psi_1S_MMERR
 - J_psi_1S_ORIVX_CHI2
 - J_psi_1S_ORIVX_COV_
 - J_psi_1S_ORIVX_NDOF
 - J_psi_1S_ORIVX_X
 - J_psi_1S_ORIVX_XERR
 - J_psi_1S_ORIVX_Y
 - J_psi_1S_ORIVX_YERR
 - J_psi_1S_ORIVX_Z
 - J_psi_1S_ORIVX_ZERR
 - J_psi_1S_OWNPV_CHI2
 - J_psi_1S_OWNPV_COV_
 - J_psi_1S_OWNPV_NDOF
 - J_psi_1S_OWNPV_X
 - J_psi_1S_OWNPV_XERR
 - J_psi_1S_OWNPV_Y
 - J_psi_1S_OWNPV_YERR
 - J_psi_1S_OWNPV_Z
 - J_psi_1S_OWNPV_ZERR
 - J_psi_1S_P
 - J_psi_1S_PE
 - J_psi_1S_PT
 - J_psi_1S_PX
 - J_psi_1S_PY
 - J_psi_1S_PZ
 - Kplus_ID
 - Kplus_IPCHI2_OWNPV
 - Kplus_IP_OWNPV
 - Kplus_M
 - Kplus_MC12TuneV2_ProbNNe
 - Kplus_MC12TuneV2_ProbNNghost
 - Kplus_MC12TuneV2_ProbNNk
 - Kplus_MC12TuneV2_ProbNNmu
 - Kplus_MC12TuneV2_ProbNNp
 - Kplus_MC12TuneV2_ProbNNpi
 - Kplus_MC12TuneV3_ProbNNe
 - Kplus_MC12TuneV3_ProbNNghost
 - Kplus_MC12TuneV3_ProbNNk
 - Kplus_MC12TuneV3_ProbNNmu
 - Kplus_MC12TuneV3_ProbNNp
 - Kplus_MC12TuneV3_ProbNNpi
 - Kplus_MC12TuneV4_ProbNNe
 - Kplus_MC12TuneV4_ProbNNghost
 - Kplus_MC12TuneV4_ProbNNk
 - Kplus_MC12TuneV4_ProbNNmu
 - Kplus_MC12TuneV4_ProbNNp
 - Kplus_MC12TuneV4_ProbNNpi
 - Kplus_MC15TuneV1_ProbNNe
 - Kplus_MC15TuneV1_ProbNNghost
 - Kplus_MC15TuneV1_ProbNNk
 - Kplus_MC15TuneV1_ProbNNmu
 - Kplus_MC15TuneV1_ProbNNp
 - Kplus_MC15TuneV1_ProbNNpi
 - Kplus_ORIVX_CHI2
 - Kplus_ORIVX_COV_
 - Kplus_ORIVX_NDOF
 - Kplus_ORIVX_X
 - Kplus_ORIVX_XERR
 - Kplus_ORIVX_Y
 - Kplus_ORIVX_YERR
 - Kplus_ORIVX_Z
 - Kplus_ORIVX_ZERR
 - Kplus_OWNPV_CHI2
 - Kplus_OWNPV_COV_
 - Kplus_OWNPV_NDOF
 - Kplus_OWNPV_X
 - Kplus_OWNPV_XERR
 - Kplus_OWNPV_Y
 - Kplus_OWNPV_YERR
 - Kplus_OWNPV_Z
 - Kplus_OWNPV_ZERR
 - Kplus_P
 - Kplus_PE
 - Kplus_PIDK
 - Kplus_PIDd
 - Kplus_PIDe
 - Kplus_PIDmu
 - Kplus_PIDp
 - Kplus_PT
 - Kplus_PX
 - Kplus_PY
 - Kplus_PZ
 - Kplus_ProbNNd
 - Kplus_ProbNNe
 - Kplus_ProbNNghost
 - Kplus_ProbNNk
 - Kplus_ProbNNmu
 - Kplus_ProbNNp
 - Kplus_ProbNNpi
 - Kplus_RichAboveElThres
 - Kplus_RichAboveKaThres
 - Kplus_RichAboveMuThres
 - Kplus_RichAbovePiThres
 - Kplus_RichAbovePrThres
 - Kplus_UsedRich1Gas
 - Kplus_UsedRich2Gas
 - Kplus_UsedRichAerogel
 - Kplus_hasCalo
 - Kplus_hasMuon
 - Kplus_hasRich
 - Kplus_isMuon
 - L0DUTCK
 - OdinTCK
 - Polarity
 - eventNumber
 - muminus_ID
 - muminus_IPCHI2_OWNPV
 - muminus_IP_OWNPV
 - muminus_M
 - muminus_MC12TuneV2_ProbNNe
 - muminus_MC12TuneV2_ProbNNghost
 - muminus_MC12TuneV2_ProbNNk
 - muminus_MC12TuneV2_ProbNNmu
 - muminus_MC12TuneV2_ProbNNp
 - muminus_MC12TuneV2_ProbNNpi
 - muminus_MC12TuneV3_ProbNNe
 - muminus_MC12TuneV3_ProbNNghost
 - muminus_MC12TuneV3_ProbNNk
 - muminus_MC12TuneV3_ProbNNmu
 - muminus_MC12TuneV3_ProbNNp
 - muminus_MC12TuneV3_ProbNNpi
 - muminus_MC12TuneV4_ProbNNe
 - muminus_MC12TuneV4_ProbNNghost
 - muminus_MC12TuneV4_ProbNNk
 - muminus_MC12TuneV4_ProbNNmu
 - muminus_MC12TuneV4_ProbNNp
 - muminus_MC12TuneV4_ProbNNpi
 - muminus_MC15TuneV1_ProbNNe
 - muminus_MC15TuneV1_ProbNNghost
 - muminus_MC15TuneV1_ProbNNk
 - muminus_MC15TuneV1_ProbNNmu
 - muminus_MC15TuneV1_ProbNNp
 - muminus_MC15TuneV1_ProbNNpi
 - muminus_ORIVX_CHI2
 - muminus_ORIVX_COV_
 - muminus_ORIVX_NDOF
 - muminus_ORIVX_X
 - muminus_ORIVX_XERR
 - muminus_ORIVX_Y
 - muminus_ORIVX_YERR
 - muminus_ORIVX_Z
 - muminus_ORIVX_ZERR
 - muminus_OWNPV_CHI2
 - muminus_OWNPV_COV_
 - muminus_OWNPV_NDOF
 - muminus_OWNPV_X
 - muminus_OWNPV_XERR
 - muminus_OWNPV_Y
 - muminus_OWNPV_YERR
 - muminus_OWNPV_Z
 - muminus_OWNPV_ZERR
 - muminus_P
 - muminus_PE
 - muminus_PIDK
 - muminus_PIDd
 - muminus_PIDe
 - muminus_PIDmu
 - muminus_PIDp
 - muminus_PT
 - muminus_PX
 - muminus_PY
 - muminus_PZ
 - muminus_ProbNNd
 - muminus_ProbNNe
 - muminus_ProbNNghost
 - muminus_ProbNNk
 - muminus_ProbNNmu
 - muminus_ProbNNp
 - muminus_ProbNNpi
 - muminus_RichAboveElThres
 - muminus_RichAboveKaThres
 - muminus_RichAboveMuThres
 - muminus_RichAbovePiThres
 - muminus_RichAbovePrThres
 - muminus_UsedRich1Gas
 - muminus_UsedRich2Gas
 - muminus_UsedRichAerogel
 - muminus_hasCalo
 - muminus_hasMuon
 - muminus_hasRich
 - muminus_isMuon
 - muplus_ID
 - muplus_IPCHI2_OWNPV
 - muplus_IP_OWNPV
 - muplus_M
 - muplus_MC12TuneV2_ProbNNe
 - muplus_MC12TuneV2_ProbNNghost
 - muplus_MC12TuneV2_ProbNNk
 - muplus_MC12TuneV2_ProbNNmu
 - muplus_MC12TuneV2_ProbNNp
 - muplus_MC12TuneV2_ProbNNpi
 - muplus_MC12TuneV3_ProbNNe
 - muplus_MC12TuneV3_ProbNNghost
 - muplus_MC12TuneV3_ProbNNk
 - muplus_MC12TuneV3_ProbNNmu
 - muplus_MC12TuneV3_ProbNNp
 - muplus_MC12TuneV3_ProbNNpi
 - muplus_MC12TuneV4_ProbNNe
 - muplus_MC12TuneV4_ProbNNghost
 - muplus_MC12TuneV4_ProbNNk
 - muplus_MC12TuneV4_ProbNNmu
 - muplus_MC12TuneV4_ProbNNp
 - muplus_MC12TuneV4_ProbNNpi
 - muplus_MC15TuneV1_ProbNNe
 - muplus_MC15TuneV1_ProbNNghost
 - muplus_MC15TuneV1_ProbNNk
 - muplus_MC15TuneV1_ProbNNmu
 - muplus_MC15TuneV1_ProbNNp
 - muplus_MC15TuneV1_ProbNNpi
 - muplus_ORIVX_CHI2
 - muplus_ORIVX_COV_
 - muplus_ORIVX_NDOF
 - muplus_ORIVX_X
 - muplus_ORIVX_XERR
 - muplus_ORIVX_Y
 - muplus_ORIVX_YERR
 - muplus_ORIVX_Z
 - muplus_ORIVX_ZERR
 - muplus_OWNPV_CHI2
 - muplus_OWNPV_COV_
 - muplus_OWNPV_NDOF
 - muplus_OWNPV_X
 - muplus_OWNPV_XERR
 - muplus_OWNPV_Y
 - muplus_OWNPV_YERR
 - muplus_OWNPV_Z
 - muplus_OWNPV_ZERR
 - muplus_P
 - muplus_PE
 - muplus_PIDK
 - muplus_PIDd
 - muplus_PIDe
 - muplus_PIDmu
 - muplus_PIDp
 - muplus_PT
 - muplus_PX
 - muplus_PY
 - muplus_PZ
 - muplus_ProbNNd
 - muplus_ProbNNe
 - muplus_ProbNNghost
 - muplus_ProbNNk
 - muplus_ProbNNmu
 - muplus_ProbNNp
 - muplus_ProbNNpi
 - muplus_RichAboveElThres
 - muplus_RichAboveKaThres
 - muplus_RichAboveMuThres
 - muplus_RichAbovePiThres
 - muplus_RichAbovePrThres
 - muplus_UsedRich1Gas
 - muplus_UsedRich2Gas
 - muplus_UsedRichAerogel
 - muplus_hasCalo
 - muplus_hasMuon
 - muplus_hasRich
 - muplus_isMuon
 - nCandidate
 - runNumber
 - totCandidates
Lista de ramas guardada en: /home/karna/Documentos/PF/MadGraph/assset/txt/branches/dvntuple_01.txt

['BCID',
 'BCType',
 'Bplus_DIRA_OWNPV',
 'Bplus_ENDVERTEX_CHI2',
 'Bplus_ENDVERTEX_COV_',
 'Bplus_ENDVERTEX_NDOF',
 'Bplus_ENDVERTEX_X',
 'Bplus_ENDVERTEX_XERR',
 'Bplus_ENDVERTEX_Y',
 'Bplus_ENDVERTEX_YERR',
 'Bplus_ENDVERTEX_Z',
 'Bplus_ENDVERTEX_ZERR',
 'Bplus_FDCHI2_OWNPV',
 'Bplus_FD_OWNPV',
 'Bplus_ID',
 'Bplus_IPCHI2_OWNPV',
 'Bplus_IP_OWNPV',
 'Bplus_M',
 'Bplus_MM',
 'Bplus_MMERR',
 'Bplus_OWNPV_CHI2',
 'Bplus_OWNPV_COV_',
 'Bplus_OWNPV_NDOF',
 'Bplus_OWNPV_X',
 'Bplus_OWNPV_XERR',
 'Bplus_OWNPV_Y',
 'Bplus_OWNPV_YERR',
 'Bplus_OWNPV_Z',
 'Bplus_OWNPV_ZERR',
 'Bplus_P',
 'Bplus_PE',
 'Bplus_PT',
 'Bplus_PX',
 'Bplus_PY',
 'Bplus_PZ',
 'EventInSequence',
 'GpsTime',
 'HLT1TCK',
 'HLT2TCK',
 'J_psi_1S_DIRA_ORIVX',
 'J_psi_1S_DIRA_OWNPV',
 'J_psi_1S_ENDVERTEX_CHI2',
 'J_psi_1S_ENDVERTEX_COV_',
 'J_psi_1S_ENDVERTEX_NDOF',
 'J_psi_1S_ENDVERTEX_X',
 'J_psi_1S_ENDVERTEX_XERR',
 'J_psi_1S_ENDVERTEX_Y',
 'J_psi_1S_ENDVERTEX_YERR',
 'J_psi_1S_ENDVERTEX_Z',
 'J_psi_1S_ENDVERTEX_ZERR',
 'J_psi_1S_FDCHI2_ORIVX',
 'J_psi_1S_FDCHI2_OWNPV',
 'J_psi_1S_FD_ORIVX',
 'J_psi_1S_FD_OWNPV',
 'J_psi_1S_ID',
 'J_psi_1S_IPCHI2_OWNPV',
 'J_psi_1S_IP_OWNPV',
 'J_psi_1S_M',
 'J_psi_1S_MM',
 'J_psi_1S_MMERR',
 'J_psi_1S_ORIVX_CHI2',
 'J_psi_1S_ORIVX_COV_',
 'J_psi_1S_ORIVX_NDOF',
 'J_psi_1S_ORIVX_X',
 'J_psi_1S_ORIVX_XERR',
 'J_psi_1S_ORIVX_Y',
 'J_psi_1S_ORIVX_YERR',
 'J_psi_1S_ORIVX_Z',
 'J_psi_1S_ORIVX_ZERR',
 'J_psi_1S_OWNPV_CHI2',
 'J_psi_1S_OWNPV_COV_',
 'J_psi_1S_OWNPV_NDOF',
 'J_psi_1S_OWNPV_X',
 'J_psi_1S_OWNPV_XERR',
 'J_psi_1S_OWNPV_Y',
 'J_psi_1S_OWNPV_YERR',
 'J_psi_1S_OWNPV_Z',
 'J_psi_1S_OWNPV_ZERR',
 'J_psi_1S_P',
 'J_psi_1S_PE',
 'J_psi_1S_PT',
 'J_psi_1S_PX',
 'J_psi_1S_PY',
 'J_psi_1S_PZ',
 'Kplus_ID',
 'Kplus_IPCHI2_OWNPV',
 'Kplus_IP_OWNPV',
 'Kplus_M',
 'Kplus_MC12TuneV2_ProbNNe',
 'Kplus_MC12TuneV2_ProbNNghost',
 'Kplus_MC12TuneV2_ProbNNk',
 'Kplus_MC12TuneV2_ProbNNmu',
 'Kplus_MC12TuneV2_ProbNNp',
 'Kplus_MC12TuneV2_ProbNNpi',
 'Kplus_MC12TuneV3_ProbNNe',
 'Kplus_MC12TuneV3_ProbNNghost',
 'Kplus_MC12TuneV3_ProbNNk',
 'Kplus_MC12TuneV3_ProbNNmu',
 'Kplus_MC12TuneV3_ProbNNp',
 'Kplus_MC12TuneV3_ProbNNpi',
 'Kplus_MC12TuneV4_ProbNNe',
 'Kplus_MC12TuneV4_ProbNNghost',
 'Kplus_MC12TuneV4_ProbNNk',
 'Kplus_MC12TuneV4_ProbNNmu',
 'Kplus_MC12TuneV4_ProbNNp',
 'Kplus_MC12TuneV4_ProbNNpi',
 'Kplus_MC15TuneV1_ProbNNe',
 'Kplus_MC15TuneV1_ProbNNghost',
 'Kplus_MC15TuneV1_ProbNNk',
 'Kplus_MC15TuneV1_ProbNNmu',
 'Kplus_MC15TuneV1_ProbNNp',
 'Kplus_MC15TuneV1_ProbNNpi',
 'Kplus_ORIVX_CHI2',
 'Kplus_ORIVX_COV_',
 'Kplus_ORIVX_NDOF',
 'Kplus_ORIVX_X',
 'Kplus_ORIVX_XERR',
 'Kplus_ORIVX_Y',
 'Kplus_ORIVX_YERR',
 'Kplus_ORIVX_Z',
 'Kplus_ORIVX_ZERR',
 'Kplus_OWNPV_CHI2',
 'Kplus_OWNPV_COV_',
 'Kplus_OWNPV_NDOF',
 'Kplus_OWNPV_X',
 'Kplus_OWNPV_XERR',
 'Kplus_OWNPV_Y',
 'Kplus_OWNPV_YERR',
 'Kplus_OWNPV_Z',
 'Kplus_OWNPV_ZERR',
 'Kplus_P',
 'Kplus_PE',
 'Kplus_PIDK',
 'Kplus_PIDd',
 'Kplus_PIDe',
 'Kplus_PIDmu',
 'Kplus_PIDp',
 'Kplus_PT',
 'Kplus_PX',
 'Kplus_PY',
 'Kplus_PZ',
 'Kplus_ProbNNd',
 'Kplus_ProbNNe',
 'Kplus_ProbNNghost',
 'Kplus_ProbNNk',
 'Kplus_ProbNNmu',
 'Kplus_ProbNNp',
 'Kplus_ProbNNpi',
 'Kplus_RichAboveElThres',
 'Kplus_RichAboveKaThres',
 'Kplus_RichAboveMuThres',
 'Kplus_RichAbovePiThres',
 'Kplus_RichAbovePrThres',
 'Kplus_UsedRich1Gas',
 'Kplus_UsedRich2Gas',
 'Kplus_UsedRichAerogel',
 'Kplus_hasCalo',
 'Kplus_hasMuon',
 'Kplus_hasRich',
 'Kplus_isMuon',
 'L0DUTCK',
 'OdinTCK',
 'Polarity',
 'eventNumber',
 'muminus_ID',
 'muminus_IPCHI2_OWNPV',
 'muminus_IP_OWNPV',
 'muminus_M',
 'muminus_MC12TuneV2_ProbNNe',
 'muminus_MC12TuneV2_ProbNNghost',
 'muminus_MC12TuneV2_ProbNNk',
 'muminus_MC12TuneV2_ProbNNmu',
 'muminus_MC12TuneV2_ProbNNp',
 'muminus_MC12TuneV2_ProbNNpi',
 'muminus_MC12TuneV3_ProbNNe',
 'muminus_MC12TuneV3_ProbNNghost',
 'muminus_MC12TuneV3_ProbNNk',
 'muminus_MC12TuneV3_ProbNNmu',
 'muminus_MC12TuneV3_ProbNNp',
 'muminus_MC12TuneV3_ProbNNpi',
 'muminus_MC12TuneV4_ProbNNe',
 'muminus_MC12TuneV4_ProbNNghost',
 'muminus_MC12TuneV4_ProbNNk',
 'muminus_MC12TuneV4_ProbNNmu',
 'muminus_MC12TuneV4_ProbNNp',
 'muminus_MC12TuneV4_ProbNNpi',
 'muminus_MC15TuneV1_ProbNNe',
 'muminus_MC15TuneV1_ProbNNghost',
 'muminus_MC15TuneV1_ProbNNk',
 'muminus_MC15TuneV1_ProbNNmu',
 'muminus_MC15TuneV1_ProbNNp',
 'muminus_MC15TuneV1_ProbNNpi',
 'muminus_ORIVX_CHI2',
 'muminus_ORIVX_COV_',
 'muminus_ORIVX_NDOF',
 'muminus_ORIVX_X',
 'muminus_ORIVX_XERR',
 'muminus_ORIVX_Y',
 'muminus_ORIVX_YERR',
 'muminus_ORIVX_Z',
 'muminus_ORIVX_ZERR',
 'muminus_OWNPV_CHI2',
 'muminus_OWNPV_COV_',
 'muminus_OWNPV_NDOF',
 'muminus_OWNPV_X',
 'muminus_OWNPV_XERR',
 'muminus_OWNPV_Y',
 'muminus_OWNPV_YERR',
 'muminus_OWNPV_Z',
 'muminus_OWNPV_ZERR',
 'muminus_P',
 'muminus_PE',
 'muminus_PIDK',
 'muminus_PIDd',
 'muminus_PIDe',
 'muminus_PIDmu',
 'muminus_PIDp',
 'muminus_PT',
 'muminus_PX',
 'muminus_PY',
 'muminus_PZ',
 'muminus_ProbNNd',
 'muminus_ProbNNe',
 'muminus_ProbNNghost',
 'muminus_ProbNNk',
 'muminus_ProbNNmu',
 'muminus_ProbNNp',
 'muminus_ProbNNpi',
 'muminus_RichAboveElThres',
 'muminus_RichAboveKaThres',
 'muminus_RichAboveMuThres',
 'muminus_RichAbovePiThres',
 'muminus_RichAbovePrThres',
 'muminus_UsedRich1Gas',
 'muminus_UsedRich2Gas',
 'muminus_UsedRichAerogel',
 'muminus_hasCalo',
 'muminus_hasMuon',
 'muminus_hasRich',
 'muminus_isMuon',
 'muplus_ID',
 'muplus_IPCHI2_OWNPV',
 'muplus_IP_OWNPV',
 'muplus_M',
 'muplus_MC12TuneV2_ProbNNe',
 'muplus_MC12TuneV2_ProbNNghost',
 'muplus_MC12TuneV2_ProbNNk',
 'muplus_MC12TuneV2_ProbNNmu',
 'muplus_MC12TuneV2_ProbNNp',
 'muplus_MC12TuneV2_ProbNNpi',
 'muplus_MC12TuneV3_ProbNNe',
 'muplus_MC12TuneV3_ProbNNghost',
 'muplus_MC12TuneV3_ProbNNk',
 'muplus_MC12TuneV3_ProbNNmu',
 'muplus_MC12TuneV3_ProbNNp',
 'muplus_MC12TuneV3_ProbNNpi',
 'muplus_MC12TuneV4_ProbNNe',
 'muplus_MC12TuneV4_ProbNNghost',
 'muplus_MC12TuneV4_ProbNNk',
 'muplus_MC12TuneV4_ProbNNmu',
 'muplus_MC12TuneV4_ProbNNp',
 'muplus_MC12TuneV4_ProbNNpi',
 'muplus_MC15TuneV1_ProbNNe',
 'muplus_MC15TuneV1_ProbNNghost',
 'muplus_MC15TuneV1_ProbNNk',
 'muplus_MC15TuneV1_ProbNNmu',
 'muplus_MC15TuneV1_ProbNNp',
 'muplus_MC15TuneV1_ProbNNpi',
 'muplus_ORIVX_CHI2',
 'muplus_ORIVX_COV_',
 'muplus_ORIVX_NDOF',
 'muplus_ORIVX_X',
 'muplus_ORIVX_XERR',
 'muplus_ORIVX_Y',
 'muplus_ORIVX_YERR',
 'muplus_ORIVX_Z',
 'muplus_ORIVX_ZERR',
 'muplus_OWNPV_CHI2',
 'muplus_OWNPV_COV_',
 'muplus_OWNPV_NDOF',
 'muplus_OWNPV_X',
 'muplus_OWNPV_XERR',
 'muplus_OWNPV_Y',
 'muplus_OWNPV_YERR',
 'muplus_OWNPV_Z',
 'muplus_OWNPV_ZERR',
 'muplus_P',
 'muplus_PE',
 'muplus_PIDK',
 'muplus_PIDd',
 'muplus_PIDe',
 'muplus_PIDmu',
 'muplus_PIDp',
 'muplus_PT',
 'muplus_PX',
 'muplus_PY',
 'muplus_PZ',
 'muplus_ProbNNd',
 'muplus_ProbNNe',
 'muplus_ProbNNghost',
 'muplus_ProbNNk',
 'muplus_ProbNNmu',
 'muplus_ProbNNp',
 'muplus_ProbNNpi',
 'muplus_RichAboveElThres',
 'muplus_RichAboveKaThres',
 'muplus_RichAboveMuThres',
 'muplus_RichAbovePiThres',
 'muplus_RichAbovePrThres',
 'muplus_UsedRich1Gas',
 'muplus_UsedRich2Gas',
 'muplus_UsedRichAerogel',
 'muplus_hasCalo',
 'muplus_hasMuon',
 'muplus_hasRich',
 'muplus_isMuon',
 'nCandidate',
 'runNumber',
 'totCandidates']

In [5]:
io.load_dataframe(
    branches=io.txt_data('dvntuple_01'),
    dataset='dvntuple_01'
).head()

Ramas cargadas desde: /home/karna/Documentos/PF/MadGraph/analysis/dvntuple_01.txt
Cantidad de ramas: 73
Archivo: 00334560_00000001_1.dvntuple.root
Árbol seleccionado: Btree/DecayTree
Archivo: 00334560_00000002_1.dvntuple.root
Árbol seleccionado: Btree/DecayTree
Archivo: 00334564_00000001_1.dvntuple.root
Árbol seleccionado: Btree/DecayTree
Archivo: 00334565_00000001_1.dvntuple.root
Árbol seleccionado: Btree/DecayTree
Archivo: 00334566_00000001_1.dvntuple.root
Árbol seleccionado: Btree/DecayTree
Total de eventos: 5,428,778 eventos

,Bplus_M,Bplus_MM,Bplus_P,Bplus_PE,Bplus_PT,Bplus_PX,Bplus_PY,Bplus_PZ,J_psi_1S_M,J_psi_1S_MM,...,muplus_PX,muplus_PY,muplus_PZ,muplus_ProbNNd,muplus_ProbNNe,muplus_ProbNNghost,muplus_ProbNNk,muplus_ProbNNmu,muplus_ProbNNp,muplus_ProbNNpi
0,4956.729567,4945.823,158312.333790,158389.911920,12921.429881,12396.06,3647.06,157784.13,3103.313068,3103.545,...,3139.46,1011.25,25883.72,-1000.0,0.000006,0.001079,0.000136,0.997811,6.704558e-05,0.075252
1,5156.595195,5155.284,164720.708229,164801.402280,7556.089679,5422.58,5262.14,164547.31,3106.257555,3106.612,...,3054.16,3189.44,73941.85,-1000.0,0.000011,0.002751,0.012555,0.997984,3.695967e-03,0.174606
2,5254.092310,5254.820,69940.802543,70137.873837,13365.551952,12537.11,4632.37,68651.86,3079.718331,3077.909,...,5227.84,1178.88,38543.74,-1000.0,0.000001,0.000260,0.000074,0.999955,8.452535e-07,0.001824
3,5224.640083,5235.290,441587.394557,441618.301133,9904.278885,-9278.89,-3463.66,441476.31,3042.170935,3041.603,...,-1177.70,-2054.79,119046.62,-1000.0,0.000014,0.000487,0.063642,0.891807,1.384623e-02,0.051999
4,5312.555129,5315.405,454243.660832,454274.725962,18281.324367,5208.10,-17523.77,453875.64,3136.136955,3136.506,...,3881.92,-9768.66,251020.37,-1000.0,0.006428,0.000476,0.020230,0.999072,3.736996e-02,0.000961

In [7]:
p_KKK = (
    '(H1_ProbK > 0.5) & (H2_ProbK > 0.5) & (H3_ProbK > 0.5) & '
    '(H1_ProbPi < 0.5) & (H2_ProbPi < 0.5) & (H3_ProbPi < 0.5) & '
    '(H1_isMuon == 0) & (H2_isMuon == 0) & (H3_isMuon == 0)'
)
io.load_dataframe(
    branches=None,
    cut=p_KKK,
    dataset='b2hhh'
).head()

Archivo: B2HHH_MagnetUp.root
Árbol seleccionado: DecayTree
Archivo: B2HHH_MagnetDown.root
Árbol seleccionado: DecayTree
Total de eventos: 23,895 eventos

,B_FlightDistance,B_VertexChi2,H1_PX,H1_PY,H1_PZ,H1_ProbK,H1_ProbPi,H1_Charge,H1_IPChi2,H1_isMuon,...,H2_IPChi2,H2_isMuon,H3_PX,H3_PY,H3_PZ,H3_ProbK,H3_ProbPi,H3_Charge,H3_IPChi2,H3_isMuon
325,10.428140,4.056947,-4168.055539,-704.953919,24548.766576,0.771199,0.051726,-1,1002.657075,0,...,714.174519,0,-8864.962492,-7428.640292,77446.175923,0.934580,0.128720,1,536.585115,0
539,33.591307,2.220242,1295.910334,-61.956920,35569.606902,0.932006,0.058690,-1,6672.092707,0,...,737.219732,0,-341.750434,3317.423370,24380.200353,0.968883,0.129317,1,23332.453390,0
588,16.531858,11.593388,1493.048615,1944.600925,33003.915368,0.953512,0.104768,-1,1731.923563,0,...,499.998835,0,4779.029220,-287.829864,53908.496894,0.844950,0.064803,1,3484.193030,0
1086,4.102797,11.321708,-236.694032,843.809179,28207.109021,0.655129,0.045339,-1,5.033764,0,...,6.588705,0,-1085.332141,-3076.759324,30036.196827,0.912293,0.080841,1,489.046805,0
1236,3.509346,5.739399,123.873807,856.290459,51956.566616,0.940484,0.078221,-1,7.005894,0,...,2.090424,0,1639.997962,2660.275891,19441.349314,0.702135,0.028641,1,888.535134,0